cluster:
  directory: /home/rebeccac/scratch/pipeline/output/simulate_info
  name: simulate_obs
  nodes: 16
  time: 45
  ompnum: 3
  pernode: 16
  mem: 192000M
  system: cedar
  queue_sys: slurm
  account: rrg-kmsmith
pipeline:
  logging:
    root: DEBUG
    peewee: INFO
    matplotlib: INFO
    h5py: INFO
  save_versions:
  - caput
  - cora
  - draco
  - drift
  - numpy
  - scipy
  - h5py
  - mpi4py
  tasks:
  - type: draco.core.task.SetMPILogging
    params:
      level_rank0: DEBUG
      level_all: WARN
  - type: draco.core.io.LoadProductManager
    out: manager
    params:
      product_directory: /home/rebeccac/scratch/pipeline/output
  - type: draco.core.io.LoadMaps
    out: map
    params:
      maps:
      - tag: HIgalaxies
        files:
        - /home/rebeccac/scratch/pipeline/output/Up_Gal.h5
  - type: draco.synthesis.stream.SimulateSidereal
    requires: manager
    in: map
    out: sstack
    params:
      save: true
      output_name: /home/rebeccac/scratch/pipeline/output/sstream_{{tag}}.h5
  - type: draco.analysis.transform.MModeTransform
    requires: manager
    in: sstack
    out: mmodes
  - type: draco.analysis.flagging.MaskMModeData
    in: mmodes
    out: masked_mmodes
    params:
      auto_correlations: False
  - type: draco.analysis.mapmaker.DirtyMapMaker
    requires: manager
    in: masked_mmodes
    out: map_dirty
    params:
      nside: 128
      save: true
      output_name: /home/rebeccac/scratch/pipeline/output/dirty_map_{{tag}}.h5